sudo: required
language: elixir
elixir:
  - 1.4.2
otp_release:
  - 19.3
before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install libc-ares-dev libssl-dev uuid-dev
  - wget http://mosquitto.org/files/source/mosquitto-1.4.tar.gz
install:
  - tar xvzf mosquitto-1.4.tar.gz
  - cd mosquitto-1.4
  - make
  - sudo make install
  - cd ..
before_script:
  - mosquitto -d
  - MIX_ENV=test mix deps.get
script:
  - MIX_ENV=test mix test
after_script:
  - MIX_ENV=test mix coveralls.travis
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report